scholarship_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scholarship_post.urls', namespace='scholarship_post')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('password_reset/', 
        auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/', 
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scholarship_post/urls.py
from django.urls import path
from . import views
from .views import user_login_view, user_logout_view

app_name = 'scholarship_post'

urlpatterns = [
    path('user_registration/', views.user_registration, name='user-registration'),
    path('login/', views.user_login_view, name='user-login'),
    path('', views.home, name='home'),
    path('user_logout_view/', views.user_logout_view, name='user-logout'),
    
    path('scholarships_blog_list/', views.scholarships_blog_list, name='scholarship-blog-list'),
    path('add_scholarships/add/', views.add_scholarship, name='add-scholarship'),
   
    path('delete_scholarship/delete/<int:pk>/', views.delete_scholarship, name='delete-scholarship'),
    path('scholarship_detail/<int:pk>/', views.scholarship_detail, name='scholarship-detail'),
    path('scholarship_update/update/<int:pk>/', views.update_scholarship, name='update-scholarship'),
    path('impact/', views.impact, name='impact'),
    path('admin_dashboard/', views.admin_dashboard, name='admin-dashboard'),
    path('our_impact/', views.our_impact, name='our-impact'),

]

scholarship_post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image

#scholarship_blog model post
class ScholarshipPost(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    eligibility_criteria = models.TextField()
    dead_line = models.DateField(default=timezone.now)
    link = models.URLField(blank=True, max_length=255, null=True)
    created_at = models.DateField(default=timezone.now)
    created_by = models.ForeignKey(User, related_name="scholarships", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
    
#scholarship_blog model contact us
class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.IntegerField()
    message = models.TextField()
    
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Contact us"

#IMPACT MODEL
class OurImpact(models.Model):
    userImage = models.ImageField(upload_to='impact_images/', default="default.jpg", blank=False, null=False)
    userName = models.CharField(max_length=100)
    scholarshipName = models.CharField(max_length=100)
    universityName = models.CharField(max_length=100, default="Not Mentioned")
    studyProgram = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.userName
    class Meta: 
        ordering = ['-created_at']

scholarship_post/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import ScholarshipPost, ContactUs, OurImpact

#Scholarship_blog user creation form
class ScholarshipUserCreationForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your username',
        })
        self.fields['email'].widget = forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your email',
        })
        self.fields['password1'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your password',
        })
        self.fields['password2'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Confirm your password',
        })

#Scholarship_blog user login form
class ScholarshipUserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'})
    )
    
#scholarship_blog form post
class ScholarshipPostModelForm(forms.ModelForm):
    class Meta:
        model = ScholarshipPost
        fields = ['title', 'content', 'eligibility_criteria',
                'dead_line', 'link', 'created_at', 'created_by'
                ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'eligibility_criteria': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'dead_line': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'link': forms.URLInput(attrs={'class': 'form-control'}),
            'created_at': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }
        
#scholarship_blog form contact us
class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'phone_number', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }

#scholarship_blog form impact
class OurImpactForm(forms.ModelForm):
    class Meta:
        model = OurImpact
        fields = ['userImage', 'userName', 'scholarshipName', 'universityName', 'studyProgram']
        widgets = {
            'userImage': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'accept': 'images/*',
                }),
            'userName': forms.TextInput(attrs={'class': 'form-control'}),
            'scholarshipName': forms.TextInput(attrs={'class': 'form-control'}),
            'universityName': forms.TextInput(attrs={'class': 'form-control'}),
            'studyProgram': forms.TextInput(attrs={'class': 'form-control'}),
        }

scholarship_post/views.py
from django.shortcuts import render, redirect
from .forms import ScholarshipUserCreationForm, ScholarshipUserLoginForm, ScholarshipPostModelForm, ContactForm, OurImpactForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import ScholarshipPost, ContactUs, OurImpact
from django.shortcuts import get_object_or_404
from django.utils import timezone

#scholarship_blog user creation view
def user_registration(request):
    if request.method == 'POST':
        user_form = ScholarshipUserCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            login(request, user)
            return redirect('scholarship_post:user-login')
    else:
        user_form = ScholarshipUserCreationForm()
    return render(request, 'scholarship_post/user_register.html', {'user_form': user_form})

#scholarship_post user login view
def user_login_view(request):
    if request.method == 'POST':
        log_form = ScholarshipUserLoginForm(request.POST)
        if log_form.is_valid():
            username = log_form.cleaned_data['username']
            password = log_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user) 
                return redirect('scholarship_post:admin-dashboard')
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        log_form = ScholarshipUserLoginForm()

    return render(request, 'registration/login.html', {'log_form': log_form})

#scholarship_post user home view
def home(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, "Message Successfully Received!")
            return redirect('scholarship_post:home')  # redirect to avoid form resubmission
    else:
        contact_form = ContactForm()

    return render(request, 'scholarship_post/home.html', {
        'contact_form': contact_form
    })
    
#scholarship_post user logout view
def user_logout_view(request):
    logout(request) 
    return redirect('scholarship_post:home') 

#scholarship_blog scholarship lists view
def scholarships_blog_list(request):
    
    # Delete expired scholarships
    ScholarshipPost.objects.filter(dead_line__lt=timezone.now()).delete()
    
    # Fetch remaining valid scholarships
    scholarships = ScholarshipPost.objects.all().order_by('-created_at')
    return render(request,'scholarship_post/scholarship_list.html', {'scholarships': scholarships})

# Add scholarship_blog post
def add_scholarship(request):
    if request.method == 'POST':
        s_form = ScholarshipPostModelForm(request.POST)
        if s_form.is_valid():
            scholarship = s_form.save(commit=False)
            scholarship.created_by = request.user
            scholarship.save()
            messages.success(request, "scholarship post added successfully")
            return redirect('scholarship_post:scholarship-blog-list')
    else:
        s_form = ScholarshipPostModelForm()
    return render(request, 'scholarship_post/add_scholarship.html', {'s_form': s_form})
    
#scholarship_blog scholarship post deletion view
def delete_scholarship(request, pk):
    scholarship = get_object_or_404(ScholarshipPost, pk=pk)
    if scholarship.created_by != request.user:
        messages.error(request, "You are not authorized to delete this post")
        return redirect('scholarship_post:scholarship-detail', pk=pk)

    if request.method == 'POST':
        scholarship.delete()
        messages.success(request, "Scholarship post deleted successfully")
        return redirect('scholarship_post:scholarship-blog-list')

    return render(request, 'scholarship_post/confirm_delete_post.html', {'scholarship': scholarship})

# scholarship_post detailed view
def scholarship_detail(request, pk):
    scholarship = get_object_or_404(ScholarshipPost, pk=pk)
    return render(request, 'scholarship_post/scholarship_detailed.html', {'scholarship': scholarship})

#scholarship_post update post view
@login_required
def update_scholarship(request, pk):
    scholarship = get_object_or_404(ScholarshipPost, pk=pk)
    if scholarship.created_by != request.user:
        messages.error(request, "You are not authorized to update this post")
        return redirect('scholarship_post:scholarship-detail', pk=pk)
    
    if request.method == 'POST':
        u_form = ScholarshipPostModelForm(request.POST, instance=scholarship)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, "Scholarship post updated successfully")
            return redirect('scholarship_post:scholarship-blog-list')
    else:
        u_form = ScholarshipPostModelForm(instance=scholarship)
    return render(request, 'scholarship_post/update_scholarship.html', {'u_form': u_form, 'scholarship': scholarship})

# ADMIN DASHBOARD
@login_required
def admin_dashboard(request):
    return render(request, 'scholarship_post/admin_dashboard.html')

# Impact view
def impact(request):
    if request.method == 'POST':
        impact_form = OurImpactForm(request.POST, request.FILES)
        if impact_form.is_valid():
            print(impact_form.cleaned_data['userImage'])
            impact_form.save()
            messages.success(request, "Impact added successfully")
            return redirect('scholarship_post:our-impact')
    else:
        impact_form = OurImpactForm()
    return render(request, 'scholarship_post/impact.html', {'impact_form': impact_form})

#RENDER OUR IMPACT
def our_impact(request):
    impacts = OurImpact.objects.all().order_by('-created_at')
    return render(request, 'scholarship_post/our_impact.html', {'impacts': impacts})

scholarship_post/templates/scholarship_post/add_scholarship.html
{% extends 'scholarship_post/index.html'%}
{% load static %}

{% block css%}
    <link rel="stylesheet" href="{% static 'scholarship_post/add_scholarship.css' %}">
{% endblock css%}

{% block content %}
<div class="container-md mt-3">
    <div class="row justify-content-center add-scholarship">
        <div class="col-md-8 col-lg-6 form-container col-lg-5 shadow-lg p-4 bg-white rounded">
            <p class="form-header fs-5 text-primary text-center">Add Scholarship</p>

            <form method="post" class="add">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_title" class="form-label text-primary">Title</label>
                    {{ s_form.title }}
                </div>

                <div class="mb-3">
                    <label for="id_content" class="form-label text-primary">Content</label>
                    <!-- {{ s_form.content }} -->
                    <textarea name="content" id="id_content" class="form-control" rows="5">{{ s_form.content.value|default_if_none:'' }}</textarea>
                </div>

                <div class="mb-3">
                    <label for="id_eligibility_criteria" class="form-label text-primary">Eligibility Criteria</label>
                    <!-- {{ s_form.eligibility_criteria }} -->
                    <textarea name="eligibility_criteria" id="id_eligibility_criteria" class="form-control" rows="5">{{ s_form.eligibility_criteria.value|default_if_none:'' }}</textarea>
                </div>

                <div class="mb-3">
                    <label for="id_dead_line" class="form-label text-primary">Deadline</label>
                    {{ s_form.dead_line }}
                </div>

                <div class="mb-3">
                    <label for="id_link" class="form-label text-primary">Link</label>
                    {{ s_form.link }}
                </div>

                <div class="mb-3">
                    <label for="id_created_at" class="form-label text-primary">Posted On</label>
                    {{ s_form.created_at }}
                </div>

                <div class="mb-3">
                    <label for="id_created_by" class="form-label text-primary">Posted By</label>
                    {{ s_form.created_by }}
                </div>

                <button type="submit" class="btn btn-success w-100 mb-3">Add</button>
                <div class="text-center">
                    <a href="{% url 'scholarship_post:home' %}" class="text-decoration-none">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

scholarship_post/templates/scholarship_post/admin_dashboard.html
{% extends 'scholarship_post/index.html'%}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'scholarship_post/home.css' %}">
{% endblock css%}

{% block content %}

<!--Navbar starts-->
<!-- Navbar starts -->
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-body-secondary shadow-sm fixed-top py-3">
    <div class="container-fluid">
      
      <!-- Brand -->
      <a class="navbar-brand fw-bold text-primary" href="#">Camp2Campus</a>

      <!-- Toggle Button for Mobile -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Left Links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_staff or user.is_superuser %}
          <li class="nav-item mx-2">
            <a class="nav-link text-dark fw-semibold" href="{% url 'scholarship_post:add-scholarship' %}">Add</a>
          </li>
          {% endif %}
          <li class="nav-item mx-2">
            <a class="nav-link text-dark fw-semibold" href="{% url 'scholarship_post:scholarship-blog-list' %}">Scholarships</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link text-dark fw-semibold" href="{% url 'scholarship_post:impact' %}">Impact</a>
          </li>
        </ul>

        <!-- Right Links -->
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="btn btn-outline-primary fw-semibold" href="{% url 'scholarship_post:user-logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<!--Navbar ends-->

<div class="container text-start text-md-center mt-4 ">
    <p class="username mt-2 welcome">Hello {{ user.username }}
        <i class="fa-regular fa-hand text-warning fs-4"></i>
    </p>
    <h1 class="fs-4 text-primary welcome fw-bolder">Welcome to Camp2Campus<br>
    </h1>
    <span class="fs-6 username text-dark">You are viewing this page as an Admin!</span>
</div>
{% endblock content %}

scholarship_post/templates/scholarship_post/confirm_delete_post.html
{% extends 'scholarship_post/index.html'%}
{% load static %}

{% block css%}
    <link rel="stylesheet" href="{% static 'scholarship_post/delete.css' %}">
{% endblock css%}

{% block content %}
<div class="bg-light delete-scholarship">
    <div class="container-md d-flex justify-content-center align-items-center vh-100">
        <div class="col-md-6 col-lg-5 shadow-lg p-5 bg-white rounded text-center">
            <h4 class="text-danger mb-4">Confirm Deletion</h4>
            <p class="mb-4">Are you sure you want to delete the scholarship titled <br><span
                    class="text-primary fw-bold">{{ scholarship.title }}</span>?</p>

            <form method="post">
                {% csrf_token %}
                <div class="d-flex justify-content-center gap-3">
                    <button type="submit" class="btn btn-danger px-4">Delete</button>
                    <a href="{% url 'scholarship_post:scholarship-blog-list' %}"
                        class="btn btn-secondary px-4">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

scholarship_post/templates/scholarship_post/contact_us.html
{% extends 'scholarship_post/index.html'%}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'scholarship_post/contact_us.css' %}">
{% endblock css %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center contact-us">
        <div class="col-md-8 col-lg-5 shadow-sm p-4 rounded ourcontact">
            <p class="form-header fs-5 text-primary fw-bold text-center mb-3">Contact Us</p>

            {% for message in messages %}
                {% if message %}
                    <div class="{{ message.tags }} text-success text-center mt-2">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}

            <form method="POST">
                {% csrf_token %}
                {{ contact_form.as_p }}

                <button type="submit" class="btn btn-primary w-100 mb-3">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

scholarship_post/templates/scholarship_post/impact.html
{% extends 'scholarship_post/index.html'%}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'scholarship_post/impact.css' %}">
{% endblock css %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="p-4 shadow-lg rounded impact">
                <h5 class="text-start text-primary fw-bold mb-4">Share Your Impact Story</h5>

                <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
                    {% csrf_token %}
                    {{ impact_form.as_p }}

                    <div class="d-grid mt-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

scholarship_post/templates/scholarship_post/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>Camp2Campus {% block title %} {% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <script src="https://kit.fontawesome.com/caeb9ec53e.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

    <link rel="icon" type="image/x-icon" href="{% static 'media/favi.jpg' %}">

    {% block css %}

    {% endblock css %}
</head>

<body>

    {% block content %}

    {% endblock content %}
    <script src="{% static 'js_files/message.js' %}"></script>
</body>


<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

</html>

scholarship_post/templates/scholarship_post/our_impact.html
{% extends 'scholarship_post/index.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'scholarship_post/our-impact.css' %}">

{% endblock css %}

{% block content %}
<div class="container my-4">
    <h5 class="text-center fs-5 fw-bold text-primary mb-4">Our Impact Story</h5>

     {% for message in messages %}
        {% if message %}
            <div class="{{ message.tags }} text-success text-center mb-3 success-message">
                {{ message }}
            </div>
            {% endif %}
    {% endfor %}
    <div class="row g-4 justify-content-center">
        {% for impact in impacts %}
        <div class="col-md-6 col-lg-4">
            <div class="impact-card text-center">
                {% if impact.userImage.name != "default.jpg" %}
                <img src="{{ impact.userImage.url }}" alt="{{ impact.userName }}">
                {% else %}
                <img src="{% static 'scholarship_post/cheni.jpg' %}" alt="No Image Found">
                {% endif %}

                <ul class="list-unstyled text-dark">
                    <li><strong>Name:</strong> {{ impact.userName }}</li>
                    <li><strong>Scholarship:</strong> {{ impact.scholarshipName }}</li>
                    <li><strong>Institution:</strong> {{ impact.universityName }}</li>
                    <li><strong>Program of Study:</strong> {{ impact.studyProgram }}</li>
                </ul>
            </div>
        </div>
        {% empty %}
        <div class="col-12 text-center text-muted">
            <p>No impact stories available at the moment.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

scholarship_post/templates/scholarship_post/scholarship_detailed.html
{% extends 'scholarship_post/index.html'%}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'scholarship_post/scholarship_detail.css' %}">
{% endblock css %}

{% block content %}
<div class="row mt-4 scholarship-detail justify-content-center">
    <div class="col-md-5 shadow-sm p-4 rounded scholarhsip">
        
        {% if not user.is_staff and not user.is_superuser %}
            <p class="text-start fs-5 text-dark fw-bold mb-4">Submit Your Application</p>
        {% else %}
            <p class="text-start fs-5 text-dark fw-bold mb-4">Update or Delete Scholarship</p>
        {% endif %}

        <h1 class="fs-5 text-dark fw-bold mb-3">{{ scholarship.title }}</h1>
        <p class="text-dark">{{ scholarship.content|linebreaks }}</p>
        
        <p class="text-dark mb-3">
            <span class="text-dark fw-semibold">Eligibility Criteria:</span><br>
            {{ scholarship.eligibility_criteria|linenumbers|linebreaks }}
        </p>
        
        <p class="text-dark mb-2">
            <span class="text-dark fw-semibold">Deadline:</span> {{ scholarship.dead_line }}
        </p>
        
        <p class="text-dark mb-2">
            <span class="text-dark fw-semibold">Link:</span><br>
            <a href="{{ scholarship.link }}" target="_blank" class="text-decoration-none text-primary">
                {{ scholarship.link|slice:":30" }}{% if scholarship.link|length > 30 %}...{% endif %}
            </a>
        </p>
        
        <p class="text-dark mb-2"><span class="text-dark fw-semibold">Posted on:</span> {{ scholarship.created_at }}</p>
        <p class="text-dark mb-3"><span class="text-dark fw-semibold">Posted By:</span> {{ scholarship.created_by.username }}</p>

        <div class="text-center">
            <a href="{% url 'scholarship_post:scholarship-blog-list' %}" class="btn btn-primary btn-sm mx-1 w-100 mb-3">Back</a>

            {% if user.is_staff or user.is_superuser %}
                <a href="{% url 'scholarship_post:update-scholarship' scholarship.pk %}" class="btn btn-secondary btn-sm mx-1 w-100 mb-3">Update</a>
                <a href="{% url 'scholarship_post:delete-scholarship' scholarship.pk %}" class="btn btn-danger btn-sm mx-1 w-100">Delete</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

scholarship_post/templates/scholarship_post/update_scholarship.html
{% extends 'scholarship_post/index.html'%}
{% load static %}

{% block css%}
    <link rel="stylesheet" href="{% static 'scholarship_post/update.css' %}">
{% endblock css%}

{% block content %}

    <div class="row mt-2 update-scholarship">
        <div class="col-md-3">

        </div>
        <div class="col-md-6 col-lg-6 shadow-lg p-4 bg-white rounded">
            <p class="text-primary fs-5 text-center ">Update Scholarship</p>

            <form method="post">
                {% csrf_token %}
                
                <div class="mb-3">
                    <label for="id_title" class="form-label text-primary">Title</label>
                    {{ u_form.title }}
                </div>

                <div class="mb-3">
                    <label for="id_content" class="form-label text-primary">Content</label>
                    {{ u_form.content }}
                </div>

                <div class="mb-3">
                    <label for="id_eligibility_criteria" class="form-label text-primary">Eligibility Criteria</label>
                    {{ u_form.eligibility_criteria }}
                </div>

                <div class="mb-3">
                    <label for="id_dead_line" class="form-label text-primary">Deadline</label>
                    {{ u_form.dead_line }}
                </div>

                <div class="mb-3">
                    <label for="id_link" class="form-label text-primary">Link</label>
                    {{ u_form.link }}
                </div>

                <div class="mb-3">
                    <label for="id_created_at" class="form-label text-primary">Posted On</label>
                    {{ u_form.created_at }}
                </div>

                <div class="mb-3">
                    <label for="id_created_by" class="form-label text-primary">Posted By</label>
                    {{ u_form.created_by }}
                </div>

                <button type="submit" class="btn btn-success w-100 mb-2">Update</button>
            </form>

            <div class="text-center">
                <p><a href="{% url 'scholarship_post:scholarship-blog-list' %}" class="text-decoration-none">Cancel</a></p>
            </div>
            
        </div>

        <div class="col-md-3">

        </div>

    </div>
{% endblock content %}

scholarship_post/templates/scholarship_post/user_register.html
{% extends 'scholarship_post/index.html'%}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'scholarship_post/register.css' %}">
{% endblock css%}

{% block content %}
<div class="container pt-4">
    <div class="row justify-content-center custom-container">
        <div class="col-md-6 col-lg-5 shadow-lg p-4 bg-white rounded">
            <h2 class="text-center mb-2 text-primary fs-5">Camp2Campus</h2>

            {% for message in messages %}
            {% if message %}
            <div class="{{ message.tags }} text-success text-center mt-2">
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            <form method="post">
                {% csrf_token %}
                {% for field in user_form %}
                <div class="mb-3">
                    {{ field.errors }}
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary w-100 py-2 mt-2">Register</button>
                </div>
            </form>
            <div class="text-center mt-4">
                <p>Already have an account?</p>
                <a href="{% url 'scholarship_post:user-login' %}" class="text-decoration-none text-primary">Log
                    in <i class="fa-solid fa-arrow-right-to-bracket text-success fs-5"></i></a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}